### ISSUE TITLE
Finished the Pytorch implementation of this paper NeuralPull

### ISSUE THREAD

**Issue by wzxshhz123** [mabaorui/NeuralPull#1]
Hi, I have done the PyTorch implementation of your impressive work https://github.com/wzxshhz123/NeuralPull_pytorch

Would you like to cite this link?

**Comment by mabaorui** [comment]
I really appreciate your contribution to the PyTorch implementation of  NeuralPull.  As you make your code can be understood with ease, I will cite a link to your code on the platform.  Therefore, researchers who are interested can find the code in the Pytorch implementation for references.
