### ISSUE TITLE
About dataset for surface reconstruction

### ISSUE THREAD

**Issue by Runsong123** [mabaorui/NeuralPull#12]
Dear baorui,

Thansk for sharing your great work!
From my understanding, for the surface reconstruction experiments, we need one network for each shape. And the Tab.1 and Tab 2 show the metric in ABC, FAMOUS dataset and  ShapeNet. I want to make sure whether you just use the test part of  these dataset ( ABC, FAMOUS dataset and  ShapeNet) for the evaluation?

looking for your reply!

Best,
Runsong

**Comment by mabaorui** [comment]
HI Runsong，
   Thanks for your attention, in  '4.1. Surface Reconstruction' we only use the test set.

**Comment by Runsong123** [comment]
> HI Runsong， Thanks for your attention, in '4.1. Surface Reconstruction' we only use the test set.

Thanks. 
Cause there are different types in the ABC and FAMOUS dataset. (e.g. [dense, extra_noise, noisefree, original, sparse] in FAMOUS). Is the reported results calculated by average all type results?

**Comment by mabaorui** [comment]
> > HI Runsong， Thanks for your attention, in '4.1. Surface Reconstruction' we only use the test set.
> 
> Got it. Thanks for your reply. Sorry that I just notice it. And I have tried your code, the results is quite good. But I feel confused about the scale of the final mesh. Cause the input data is normalized (I mean the file is normalized before sampling), I expect the final result shoud be in the same coordinate. But it was not. Could you tell me how to set the code to make the coordinate consistent (the final mesh and input file). Many thanks in adcance. :)
Hi Runsong,
From Line 421 to Line 426, the code normalizes the mode(your output mesh from marching-cubes). 
https://github.com/mabaorui/NeuralPull/blob/a140258174d0e49a04aeec6c4702ce6639c7f0b0/NeuralPull.py#L421

**Comment by Runsong123** [comment]
> 

I see, Thanks. :)

**Comment by Runsong123** [comment]
> 

I see. Thanks again!

**Comment by Runsong123** [comment]
> 

I found the noise-free in FAMOUS is also very sparse, did the Fig 4 report the "dense" of FAMOUS. 
And how about Fig.5?

**Comment by Runsong123** [comment]
> > > HI Runsong， Thanks for your attention, in '4.1. Surface Reconstruction' we only use the test set.
> > 
> > 
> > Thanks. Cause there are different types in the ABC and FAMOUS dataset. (e.g. [dense, extra_noise, noisefree, original, sparse] in FAMOUS). Is the reported results calculated by average all type results? Sorry to bother you again.
> 
> Hi Runsong, Table 1 reported noisefree dataset. Table 9 and table 12 reported other dataset of ABC or FAMOUSE.

I found the noise-free in FAMOUS is also very sparse, did the Fig 4 report the "dense" of FAMOUS dataset?
And how about Fig.5?

**Comment by mabaorui** [comment]
> > > > HI Runsong， Thanks for your attention, in '4.1. Surface Reconstruction' we only use the test set.
> > > 
> > > 
> > > Thanks. Cause there are different types in the ABC and FAMOUS dataset. (e.g. [dense, extra_noise, noisefree, original, sparse] in FAMOUS). Is the reported results calculated by average all type results? Sorry to bother you again.
> > 
> > 
> > Hi Runsong, Table 1 reported noisefree dataset. Table 9 and table 12 reported other dataset of ABC or FAMOUSE.
> 
> I found the noise-free in FAMOUS is also very sparse, did the Fig 4 report the "dense" of FAMOUS dataset? And how about Fig.5?
Hi Runsong,
Fig 4 and Fig 5 report dense result.

**Comment by Runsong123** [comment]
Thanks very much!

Runsong
