### ISSUE TITLE
Single View Reconstruction Experiment

### ISSUE THREAD

**Issue by low5545** [mabaorui/NeuralPull#13]
Hi Baorui,

I have some questions regarding this experiment presented in Section 4.2, hope you can help me with this.

1. Is the L1 CD metric reported in Table 7 multiplied by a constant factor of 0.5, as shown [here](https://github.com/mabaorui/NeuralPull/blob/a140258174d0e49a04aeec6c4702ce6639c7f0b0/NeuralPull.py#L136)?
2. Is there any (additional) normalization applied on the point clouds obtained from the Occupancy Networks ShapeNet dataset for training & evaluation respectively? If not, does that mean the point clouds are bounded within a unit cube centered at 0 with a padding of 0.05 on all sides?
3. Is it true that only the first view for every object in the dataset is used for evaluation, as done in Occupancy Networks?

Thanks!

**Comment by mabaorui** [comment]
Hi Yonghui，
   Metric calculation and dataset preprocessing are both exactly the same with Occupancy Networks.

**Comment by low5545** [comment]
Thanks for the info!
