### ISSUE TITLE
env tensorflow1 problem

### ISSUE THREAD

**Issue by HeyamM** [mabaorui/NeuralPull#2]
Hi Mabaorui, I'm Heyam a Ph.D. student and I'm interested in your paper and I want to run your code properly. I have downloaded Anaconda3 on Centos 8  with python3 3.8.8 and I have to run the first two couple lines of your code to start run the cod but I have a problem that's related to packages that are not resolved, I will attach the photo of the error, could you help me, please to fix this error because I don't know what is the problem?
![NeuralPullProblem](https://user-images.githubusercontent.com/83015730/125780957-f00a83c7-cdbd-4cfd-aeef-f88b8ebe5f08.jpeg)
Thanks 
Heyam Maraha

**Comment by mabaorui** [comment]
If you operating system supports python=3.6.13 and tensorflow=2.5.0，I offer you another solution: 1. Download this file https://drive.google.com/drive/folders/1N7ZFI_eFsBEpO6ra0G9Bzc5PurSexoww?usp=sharing 2. Run this command ‘conda env create -f NeuralPull.yml’ 3. Run this command ‘source activate tensorflow’ 4. Replace this line of code  ‘import tensorflow as tf’ in NeuralPull.py and 
sample_query_point.py with ‘import tensorflow.compat.v1 as tf


tf.disable_v2_behavior()’
If you still have problems, please feel free to contact me.
<img width="260" alt="Snipaste_2021-07-15_20-20-14" src="https://user-images.githubusercontent.com/14806520/125787219-5e61e956-66ad-46cc-ae9e-df82cf212b18.png">

**Comment by mabaorui** [comment]
If you operating system supports python=3.6.13 and tensorflow=2.5.0，I offer you another solution: 1. Download this file https://drive.google.com/drive/folders/1N7ZFI_eFsBEpO6ra0G9Bzc5PurSexoww?usp=sharing 2. Run this command ‘conda env create -f NeuralPull.yml’ 3. Run this command ‘source activate tensorflow’ 4. Replace this line of code ‘import tensorflow as tf’ in NeuralPull.py and
sample_query_point.py with ‘import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()’
If you still have problems, please feel free to contact me.
<img width="260" alt="Snipaste_2021-07-15_20-20-14" src="https://user-images.githubusercontent.com/14806520/125787887-cbcc9581-35b2-4584-a868-b2676c0c20ed.png">

**Comment by HeyamM** [comment]
Thanks very much..
I have made as you say for the first 2 command lines, and as result, I have 3 environments, the first is base for anaconda, the second is env for the first line of command, the last one is called TensorFlow for the second command line.
Now I'm facing another problem in the third command line which is 'python setup.py build_ext --inplace', I have implemented it in the env. of the first command, is that right or I'm in the wrong direction?
the error that I have is like
![WhatsApp Image 2021-07-27 at 2 01 30 AM](https://user-images.githubusercontent.com/83015730/127070708-92105252-8f9a-44aa-a082-39018758111b.jpeg)
 the photo is attached below, could you help me, please?
thanks for your efforts.
Heyam
