### ISSUE TITLE
Surface reconstruction

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [mabaorui/NeuralPull#5]
Hi,

Thanks a lot for the code release, I greatly enjoyed your paper. 
I would like to experiment with surface reconstruction on my own pointclouds and ran into a few issues.

As per my understanding from your pape, NeuralPull does not  condition the surface reconstruction  on anything : 

```
We do not leverage any condition c in Fig. 1 and overfit the neural network
to the shape by minimizing the loss in Eq. 2
```

However, the surface reconstruction [script](https://github.com/mabaorui/NeuralPull/blob/master/NeuralPull.py#L303
) seems to be conditioning the reconstruction on a code, and learning surface reconstruction jointly?

Ideally, to test NeuralPull, it would be great if the repo included a script that takes a pointcloud as input, fits neuralPull and returns a mesh.

I am sorry if I misunderstood the code and thanks a lot for your help,

Thibault

**Comment by mabaorui** [comment]
If you want to input a point cloud and run the script to return a mesh.
There are three steps you need to follow:
1. Prepare data from the input point cloud.
python sample_query_point --out_dir ./output_data/ --CUDA 0 --dataset other --input_dir ./input_pointcloud/
Note:The input point cloud should be put into  ./input_pointcloud/ folder.
2. Use the data prepared in step 1 to train the network.
python NeuralPull.py --data_dir ./output_data/ --out_dir ./output_network/ --class_idx 02691156 --train --dataset other
3. Test the trained network in step 2 and output the mesh.
python NeuralPull.py --data_dir ./output_data/ --out_dir ./output_network/ --class_idx 02691156 --dataset other

After completing the above three steps, you will get the reconstructed mesh model in the ./output_network/ folder.
Thank you for your attention, please contact me if you have any questions.
