### ISSUE TITLE
Threshold for surface reconstruction 

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [mabaorui/NeuralPull#8]
Hi @mabaorui,

Congrats again and sorry for the repeated queries. I am still trying to figure out a few aspects of the method and am thus opening various discussions, I hope that is ok.

I have been experimenting for surface reconstruction using the Pytorch version of the code. As you know : bearprin/neuralpull-pytorch#2

I observe that the results are better with a threshold of 0.005 than 0. Some large chunks of the shapes are sometimes not reconstructed with a threshold of 0.

Does this mean that the fitted SDF has converged to an unsigned distance function?

Thanks a lot,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Thanks for your explanation! I agree weird things can happen is the discretization is coarse. 
Best regards,
Thibault

**Comment by Colin97** [comment]
@mabaorui May I know what threshold do you use for extracting the surface in your experiments?
